globals:
  describe: true
  it: true
  cy: true
  context: true
  beforeEach: true
  Cypress: true
  expect: true
  assert: true
rules:
  no-restricted-syntax: off
  spaced-comment: off
  import/no-extraneous-dependencies: off
